SELECT
CONCAT(info_Paciente.nombre1,' ',info_Paciente.nombre2,' ',info_Paciente.apellido1,' ',info_Paciente.apellido2) AS nombre,
f_nombrePDM(info_Paciente.id_pais_nac,0) AS pais_nac,
f_nombrePDM(info_Paciente.id_pais_res,0) AS pais_res,
f_nombrePDM(info_Paciente.id_dpto_res,1) AS dpto_res,
f_nombrePDM(info_Paciente.id_mun_res,2) AS mun_res,
f_nombrePDM(info_Paciente.id,3) AS nombre_entidad,
causas_admision(info_Admision.causaExterna,0) AS causaExterna,
causas_admision(info_Admision.estadoIngreso,1) AS estadoIngreso,
causas_admision(info_Admision.mediodeingreso,2) AS mediodeingreso,
otrosDatosAdmision(info_Admision.id) AS otrosDatos,
info_Admision.id,
info_Paciente.tipo_doc,
info_Paciente.num_doc,
info_Paciente.hc,
info_Paciente.fecha_nacimiento,
info_Admision.edad,
info_Paciente.genero,
info_Paciente.estado_civil,
info_Paciente.barrio_o_vereda,
info_Paciente.direccion_ppal,
info_Paciente.ocupacion,
info_Paciente.telefono,
info_Paciente.num_celular,
info_Paciente.zona_res,
info_Paciente.estrato_se,
info_Paciente.tipo_afiliacion,
info_Paciente.nivel,
info_Admision.fecha_ingreso,
info_Admision.hora_ingreso,
info_historiac.motivo_consulta,
info_historiac.nivel_triaje,
info_historiac.alergias,
info_historiac.ingresos_previos,
info_historiac.traumatismos,
info_historiac.tratamientos,
info_historiac.dm,
info_historiac.hta,
info_historiac.dislipidemia,
info_historiac.desc_hdd,
info_historiac.tabaco,
info_historiac.alcohol,
info_historiac.droga,
info_historiac.otros_habitos,
info_historiac.situacion_basal,
info_historiac.ant_familiares,
info_historiac.enfermedad_actual,
info_hc_expfisica.ta,
info_hc_expfisica.tam,
info_hc_expfisica.fc,
info_hc_expfisica.fr,
info_hc_expfisica.t,
info_hc_expfisica.sao2,
info_hc_expfisica.pvc,
info_hc_expfisica.pic,
info_hc_expfisica.peso,
info_hc_expfisica.talla,
info_hc_expfisica.otros,
info_hc_expfisica.aspectogeneral,
info_hc_expfisica.cara,
info_hc_expfisica.cardio,
info_hc_expfisica.respiratorio,
info_hc_expfisica.gastro,
info_hc_expfisica.renal,
info_hc_expfisica.hemato,
info_hc_expfisica.endo,
info_hc_expfisica.osteo,
info_historiac.hallazgo,
static_cie101.id AS static_cie101_id,
static_cie101.codigo AS codigo1,
static_cie101.descripcion AS descripcion1,
static_cie102.id AS static_cie102_id,
static_cie102.codigo AS codigo2,
static_cie102.descripcion AS descripcion2,
static_cie103.id AS static_cie103_id,
static_cie103.codigo AS codigo3,
static_cie103.descripcion AS descripcion3,
static_cie104.id AS static_cie104_id,
static_cie104.codigo AS codigo4,
static_cie104.descripcion AS descripcion4,
static_cie105.id AS static_cie105_id,
static_cie105.codigo AS codigo5,
static_cie105.descripcion AS descripcion5,
Config_decripcion_login.nombres AS nombres,
Config_decripcion_login.apellidos AS apellidos,
Config_decripcion_login.ruta_firma AS ruta_firma
FROM
info_historiac
INNER JOIN Config_decripcion_login ON info_historiac.id_usuario = Config_decripcion_login.id
INNER JOIN info_Admision ON info_historiac.id_infoadmision = info_Admision.id
INNER JOIN info_Paciente ON info_Admision.id_datos_personales = info_Paciente.id
INNER JOIN info_hc_expfisica ON info_historiac.id = info_hc_expfisica.id_infohistoriac
INNER JOIN static_cie10 AS static_cie101 ON info_historiac.diagnostico = static_cie101.id
INNER JOIN static_cie10 AS static_cie102 ON info_historiac.diagnostico2 = static_cie102.id
INNER JOIN static_cie10 AS static_cie103 ON info_historiac.diagnostico3 = static_cie103.id
INNER JOIN static_cie10 AS static_cie104 ON info_historiac.diagnostico4 = static_cie104.id
INNER JOIN static_cie10 AS static_cie105 ON info_historiac.diagnostico5 = static_cie105.id
WHERE
     info_historiac.id = 43